apiVersion: v1
kind: Pod
metadata:
  name:  ig-controller
  namespace: metacontroller
  labels:
    app: ig-controller
spec:
  containers:
  - name: k8sdart
    image: gcr.io/engineering-devops/k8sdart
---
apiVersion: v1
kind: Service
metadata:
  name: ig-controller
  namespace: metacontroller
spec:
  type: NodePort
  selector:
    app: ig-controller
  ports:
  - port: 8080
    nodePort: 31080
#apiVersion: apps/v1beta1
#kind: Deployment
#metadata:
#  name: dscontroller
#spec:
#  replicas: 1
#  template:
#    metadata:
#      labels:
#        app: dscontroller
#    spec:
#      containers:
#      - name: dscontroller
#        image: gcr.io/engineering-devops/k8sdart
#        imagePullPolicy: IfNotPresent
#        volumeMounts:
#        - name: lib
#          mountPath: /app/lib
#      volumes:
#      - name: lib
#        configMap:
#          name: k8sdart
