apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: igdeployments.ctl.forgerock.com
spec:
  group: ctl.forgerock.com
  version: v1
  scope: Namespaced
  names:
    plural: igdeployments
    singular: igdeployment
    kind: IGDeployment
    shortNames:
    - ig
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: ig-controller
spec:
  parentResource:
    apiVersion: ctl.forgerock.com/v1
    resource: igdeployments
  childResources:
  - apiVersion: v1
    resource: services
    updateStrategy:
      method: InPlace
  - apiVersion: apps/v1beta1
    resource: deployments
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://ig-controller.metacontroller:8080/sync
