name: dart_k8s_controller
description: Simple demo to show attaching dart source at runtime
version: 0.0.1
author: Warren Strange <warren.strange@gmail.com>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  shelf: ^0.7.3+1
  json_annotation: ^0.2.5

dev_dependencies:
  test: any
  build_runner: ^0.8.9
  json_serializable: ^0.5.4
