name: dart_k8s_controller
description: Simple demo to show attaching dart source at runtime
version: 0.0.1
author: Warren Strange <warren.strange@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  args: ^0.13.7
  shelf: ^0.6.0

#dev_dependencies:
#  test: ^0.12.0
